### ISSUE TITLE
model: Ichigo-llama3.1

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/models#17]
## Goals

- llama-s should be in cortex.cpp (and Jan)

**Comment by hahuyhoang411** [comment]
Model has been converted and worked perfectly in Cortex (only text).
![Image](https://github.com/user-attachments/assets/67e8169a-f04d-49c1-9add-1b7eb1c21e66)

We need to work on the Encoder to convert speech into sound too. Close for now.
