### ISSUE TITLE
model: Mistral Nemo

### ISSUE THREAD

**Issue by offgridtech** [janhq/models#19]
### #

- [ ] I have searched the existing issues

### Current behavior

I see a bunch of stuff on HuggingFace and llama.cpp Git about pre-tokenizers causing issues upon initial release of the quantizied Mistal Nemo model, but it seemed everything was cleared up over the last few days due to a llama.cpp update.  What worked for other people didn't work for Jan.  I've tried several quant versions, and it fails to start.  Saw KoboldCPP and LMStudio say they made some updates, and it's fixed now.  I'm guessing you all need to do the same.  Thanks

More information here:
https://github.com/ggerganov/llama.cpp/pull/8579
https://github.com/ggerganov/llama.cpp/pull/8604

### Minimum reproduction step

It doesn't start.  Other models like llama 3.1 start fine.

### Expected behavior

The model starts

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/2b10685b-eea8-4a21-aea8-28aabbb7033e)

This log looks like it is the pre-tokenizer issue they were talking about.  

### Jan version

v0.5.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Environment details

AppImage on Linux

**Comment by 0xSage** [comment]
closing as done and QA'd
