### ISSUE TITLE
epic: Model Converter Pipeline

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/models#22]
## Goal

- Built-in model library has curated `model.yaml` with best parameters
- Aim for a best-in-class user experience that 
- Include system prompts that provide good experience? (may be anti-pattern)

## User Story

- We have a Model Converter that can take in a Huggingface Model repo
- Compile GGUF to a Cortex Model Repo (i.e. tag-based)
- Future: ONNX, TensorRT-LLM (using TRTLLM-Cloud) 
- Should clearly show any errors
- Should auto-populate README

## Decisions
- https://github.com/janhq/cortex.cpp/discussions/1178

### Model Compilation Pipeline
- [ ] Update Model compilation Infra
- [ ] Is there a way for us to "queue" up models?

## Future Roadmap

- Model Recommendations: can we consider recommending bigger models (e.g. q8) if hardware is strong?

**Comment by gabrielle-ong** [comment]
Marking as complete, successfully done for mistral-nemo and llama3.2
To run model converter pipeline from janhq/models repo
