### ISSUE TITLE
chore: new Models should add to Models Project Board

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/models#32]
## Goal 

- Adding issue to Models repo should also track it in Models Board
    - https://github.com/orgs/janhq/projects/5/views/63
- Objective: 
    - "What is measured is managed"
    - Allow us to track this as part of sprints, releases

**Comment by 0xSage** [comment]
Use the external link in each repo (jan/cortex), such that it links to the models board: https://ryanmulligan.dev/blog/external-links-issue-template-options/


@hahuyhoang411
