### ISSUE TITLE
Epic: Auto add tokenizer.model

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/models#34]
# Problem

Sometimes the model HF repo doesn't have tokenizer.model itself which cause the bug missing tokenizer.

# Recommendation

@nguyenhoangthuan99 : Add 1 more step in CI converter

https://github.com/ggerganov/llama.cpp/issues/2443

# Tasks
- [ ] Testing manual convert 
- [ ] Add to CI

**Comment by hahuyhoang411** [comment]
[ ] Testing manual convert 
[ ] Add to CI

**Comment by hahuyhoang411** [comment]
I think the problem is related to our current llama.cpp version

https://github.com/ggerganov/llama.cpp/issues/6419

**Comment by hahuyhoang411** [comment]
I convert the model using our internal cluster with latest llama.cpp version and it works fine

![Image](https://github.com/user-attachments/assets/8b4019a4-bfb5-4f21-a7c7-0787511e7c0c)

Can you help me to bump the version cc @nguyenhoangthuan99

**Comment by hahuyhoang411** [comment]
Problem solved with version bump

**Comment by Srujan-D** [comment]
Hi @hahuyhoang411 

I am trying to add [Florence](https://huggingface.co/microsoft/Florence-2-large/tree/main) model support to llama.cpp, and am facing the tokenizer.model issue. Can you please help out with what steps I need to follow to get tokenizer.model from tokenizer.json?

Thanks!
Srujan
